### ISSUE TITLE
proximal update

### ISSUE THREAD

**Issue by jackliu333** [hichamjanati/mtw#9]
Hi, it seems the proximal update function is different from the paper. Line 48 in solver_cd.pyx shows:
z = theta - a - b
But in the paper the corresponding component in the derived proximal operator is:
z = theta - marginal*(b+1)

Hope you could help shed light on this.

Cheers,
Liu Peng

**Comment by hichamjanati** [comment]
yes the formulas don't use the same names but they are the same, in the code the one I used is more compact. 

I think you may have confused a and alpha in proposition 3 of the paper. 
<img width="352" alt="Screenshot 2020-03-25 at 11 50 01" src="https://user-images.githubusercontent.com/17051500/77528774-c5bb0180-6e8e-11ea-9e9e-fae07815d7e0.png">
here the marginal is a. As you can see it only appears once outside the square.

So to be clear, in this proposition to retrieve the original penalty of the problem you need to set:
- alpha = gamma * mu
- a = marginal
- b = lambda / alpha

with this you get the term alpha(b+1) = lambda + mu * gamma 
so z = theta - lambda - mu * gamma

In the code I set a = mu * gamma and b = lambda (albeit some rescaling by n_samples for normalization of the hyperparameters) so you find z = theta - a - b

**Comment by jackliu333** [comment]
Thanks for your explanation! Very clear.
